#!/bin/bash

# Base setup: 6 CPUs, 1 a40 GPU, stabloe-diffusion 1.5

# Varying the number of CPUs: 1, 2, 4, 6
sbatch -J 11a4015 -o slurm_outputs/output_%j.txt -e slurm_errors/errors_%j.txt -p allgroups -n 1 -t 12:00:00 -c 1 --mem 64G --gres=gpu:a40:1 --exclude=gpu2 --wrap="cd /nfsd/lttm4/members/marx/projects/HPC-project; singularity exec --nv --bind /nfsd/lttm4/members/marx/projects/HPC-project /nfsd/lttm4/members/marx/projects/HPC-project/hpc-singularity.sif train.sh 'stable-diffusion-v1-5/stable-diffusion-v1-5' 16 8 1e-4 42 train_output_11a4015; singularity exec --nv --bind /nfsd/lttm4/members/marx/projects/HPC-project /nfsd/lttm4/members/marx/projects/HPC-project/hpc-singularity.sif python inference.py --base_model 'stable-diffusion-v1-5/stable-diffusion-v1-5' --train_output_dir train_output_11a4015 --output_dir inference_output_11a4015"
sbatch -J 21a4015 -o slurm_outputs/output_%j.txt -e slurm_errors/errors_%j.txt -p allgroups -n 1 -t 12:00:00 -c 2 --mem 64G --gres=gpu:a40:1 --exclude=gpu2 --wrap="cd /nfsd/lttm4/members/marx/projects/HPC-project; singularity exec --nv --bind /nfsd/lttm4/members/marx/projects/HPC-project /nfsd/lttm4/members/marx/projects/HPC-project/hpc-singularity.sif train.sh 'stable-diffusion-v1-5/stable-diffusion-v1-5' 16 8 1e-4 42 train_output_21a4015; singularity exec --nv --bind /nfsd/lttm4/members/marx/projects/HPC-project /nfsd/lttm4/members/marx/projects/HPC-project/hpc-singularity.sif python inference.py --base_model 'stable-diffusion-v1-5/stable-diffusion-v1-5' --train_output_dir train_output_21a4015 --output_dir inference_output_21a4015"
sbatch -J 41a4015 -o slurm_outputs/output_%j.txt -e slurm_errors/errors_%j.txt -p allgroups -n 1 -t 12:00:00 -c 4 --mem 64G --gres=gpu:a40:1 --exclude=gpu2 --wrap="cd /nfsd/lttm4/members/marx/projects/HPC-project; singularity exec --nv --bind /nfsd/lttm4/members/marx/projects/HPC-project /nfsd/lttm4/members/marx/projects/HPC-project/hpc-singularity.sif train.sh 'stable-diffusion-v1-5/stable-diffusion-v1-5' 16 8 1e-4 42 train_output_41a4015; singularity exec --nv --bind /nfsd/lttm4/members/marx/projects/HPC-project /nfsd/lttm4/members/marx/projects/HPC-project/hpc-singularity.sif python inference.py --base_model 'stable-diffusion-v1-5/stable-diffusion-v1-5' --train_output_dir train_output_41a4015 --output_dir inference_output_41a4015"
sbatch -J 61a4015 -o slurm_outputs/output_%j.txt -e slurm_errors/errors_%j.txt -p allgroups -n 1 -t 12:00:00 -c 6 --mem 64G --gres=gpu:a40:1 --exclude=gpu2 --wrap="cd /nfsd/lttm4/members/marx/projects/HPC-project; singularity exec --nv --bind /nfsd/lttm4/members/marx/projects/HPC-project /nfsd/lttm4/members/marx/projects/HPC-project/hpc-singularity.sif train.sh 'stable-diffusion-v1-5/stable-diffusion-v1-5' 16 8 1e-4 42 train_output_61a4015; singularity exec --nv --bind /nfsd/lttm4/members/marx/projects/HPC-project /nfsd/lttm4/members/marx/projects/HPC-project/hpc-singularity.sif python inference.py --base_model 'stable-diffusion-v1-5/stable-diffusion-v1-5' --train_output_dir train_output_61a4015 --output_dir inference_output_61a4015"

# Varying the number of GPUs: (1), 2, 4
sbatch -J 62a4015 -o slurm_outputs/output_%j.txt -e slurm_errors/errors_%j.txt -p allgroups -n 1 -t 12:00:00 -c 6 --mem 64G --gres=gpu:a40:2 --exclude=gpu2 --wrap="cd /nfsd/lttm4/members/marx/projects/HPC-project; singularity exec --nv --bind /nfsd/lttm4/members/marx/projects/HPC-project /nfsd/lttm4/members/marx/projects/HPC-project/hpc-singularity.sif train.sh 'stable-diffusion-v1-5/stable-diffusion-v1-5' 16 8 1e-4 42 train_output_62a4015; singularity exec --nv --bind /nfsd/lttm4/members/marx/projects/HPC-project /nfsd/lttm4/members/marx/projects/HPC-project/hpc-singularity.sif python inference.py --base_model 'stable-diffusion-v1-5/stable-diffusion-v1-5' --train_output_dir train_output_62a4015 --output_dir inference_output_62a4015"
sbatch -J 64a4015 -o slurm_outputs/output_%j.txt -e slurm_errors/errors_%j.txt -p allgroups -n 1 -t 12:00:00 -c 6 --mem 64G --gres=gpu:a40:4 --exclude=gpu2 --wrap="cd /nfsd/lttm4/members/marx/projects/HPC-project; singularity exec --nv --bind /nfsd/lttm4/members/marx/projects/HPC-project /nfsd/lttm4/members/marx/projects/HPC-project/hpc-singularity.sif train.sh 'stable-diffusion-v1-5/stable-diffusion-v1-5' 16 8 1e-4 42 train_output_64a4015; singularity exec --nv --bind /nfsd/lttm4/members/marx/projects/HPC-project /nfsd/lttm4/members/marx/projects/HPC-project/hpc-singularity.sif python inference.py --base_model 'stable-diffusion-v1-5/stable-diffusion-v1-5' --train_output_dir train_output_64a4015 --output_dir inference_output_64a4015"

# Varying the type of GPUs: (A40), RTX, L40S
sbatch -J 61rtx15 -o slurm_outputs/output_%j.txt -e slurm_errors/errors_%j.txt -p allgroups -n 1 -t 12:00:00 -c 6 --mem 64G --gres=gpu:rtx:1 --exclude=gpu2 --wrap="cd /nfsd/lttm4/members/marx/projects/HPC-project; singularity exec --nv --bind /nfsd/lttm4/members/marx/projects/HPC-project /nfsd/lttm4/members/marx/projects/HPC-project/hpc-singularity.sif train.sh 'stable-diffusion-v1-5/stable-diffusion-v1-5' 16 8 1e-4 42 train_output_61rtx15; singularity exec --nv --bind /nfsd/lttm4/members/marx/projects/HPC-project /nfsd/lttm4/members/marx/projects/HPC-project/hpc-singularity.sif python inference.py --base_model 'stable-diffusion-v1-5/stable-diffusion-v1-5' --train_output_dir train_output_61rtx15 --output_dir inference_output_61rtx15"
sbatch -J 61l40s15 -o slurm_outputs/output_%j.txt -e slurm_errors/errors_%j.txt -p allgroups -n 1 -t 12:00:00 -c 6 --mem 64G --gres=gpu:l40s:1 --exclude=gpu2 --wrap="cd /nfsd/lttm4/members/marx/projects/HPC-project; singularity exec --nv --bind /nfsd/lttm4/members/marx/projects/HPC-project /nfsd/lttm4/members/marx/projects/HPC-project/hpc-singularity.sif train.sh 'stable-diffusion-v1-5/stable-diffusion-v1-5' 16 8 1e-4 42 train_output_61l40s15; singularity exec --nv --bind /nfsd/lttm4/members/marx/projects/HPC-project /nfsd/lttm4/members/marx/projects/HPC-project/hpc-singularity.sif python inference.py --base_model 'stable-diffusion-v1-5/stable-diffusion-v1-5' --train_output_dir train_output_61l40s15 --output_dir inference_output_61l40s15"

# Varying the diffusion model: (stable-diffusion 1.5), stable-diffusion 2.1, stable-diffusion XL
sbatch -J 61a4021 -o slurm_outputs/output_%j.txt -e slurm_errors/errors_%j.txt -p allgroups -n 1 -t 12:00:00 -c 6 --mem 64G --gres=gpu:a40:1 --exclude=gpu2 --wrap="cd /nfsd/lttm4/members/marx/projects/HPC-project; singularity exec --nv --bind /nfsd/lttm4/members/marx/projects/HPC-project /nfsd/lttm4/members/marx/projects/HPC-project/hpc-singularity.sif train.sh 'sd2-community/stable-diffusion-2-1' 16 8 1e-4 42 train_output_61a4021; singularity exec --nv --bind /nfsd/lttm4/members/marx/projects/HPC-project /nfsd/lttm4/members/marx/projects/HPC-project/hpc-singularity.sif python inference.py --base_model 'sd2-community/stable-diffusion-2-1' --train_output_dir train_output_61a4021 --output_dir inference_output_61a4021"
sbatch -J 61a40xl -o slurm_outputs/output_%j.txt -e slurm_errors/errors_%j.txt -p allgroups -n 1 -t 12:00:00 -c 6 --mem 64G --gres=gpu:a40:1 --exclude=gpu2 --wrap="cd /nfsd/lttm4/members/marx/projects/HPC-project; singularity exec --nv --bind /nfsd/lttm4/members/marx/projects/HPC-project /nfsd/lttm4/members/marx/projects/HPC-project/hpc-singularity.sif train.sh 'stabilityai/stable-diffusion-xl-base-1.0' 16 8 1e-4 42 train_output_61a40xl; singularity exec --nv --bind /nfsd/lttm4/members/marx/projects/HPC-project /nfsd/lttm4/members/marx/projects/HPC-project/hpc-singularity.sif python inference.py --base_model 'stabilityai/stable-diffusion-xl-base-1.0' --train_output_dir train_output_61a40xl --output_dir inference_output_61a40xl"